// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SpeedController* chassisLeftDriveTalon;
	static SpeedController* chassisRightDriveTalon;
	static RobotDrive* chassisRobotDrive21;
	static Encoder* shooterTiltSubsystemShooterTiltEncoder;
	static SpeedController* shooterTiltSubsystemShooterTiltJaguar;
	static DigitalInput* shooterTiltSubsystemShooterTiltTopLimit;
	static DigitalInput* shooterTiltSubsystemShooterTiltBottomLimit;
	static Encoder* shooterSubsystemShooterEncoder;
	static SpeedController* shooterSubsystemShooterWheelJaguar;
	static SpeedController* frisbeePanSubsystemPanTiltJaguar;
	static Encoder* frisbeePanSubsystemPanTiltEncoder;
	static SpeedController* frisbeePanSubsystemPanInjestBeltJaguar;
	static SpeedController* frisbeePanSubsystemPanLateralBeltJaguar;
	static DigitalInput* frisbeePanSubsystemPanBottomLimit;
	static Solenoid* lEDSubsystemBlueLEDStrip;
	static Solenoid* lEDSubsystemYellowLEDStrip;
	static Solenoid* lEDSubsystemGreenLEDRIng;
	static SpeedController* kickerSubsystemKickerJaguar;
	static DigitalInput* kickerSubsystemKickerLimit;
	static SpeedController* pizzaBoxSubsystemPizzaBoxJaguar;
	static DigitalInput* pizzaBoxSubsystemPBTopLimit;
	static DigitalInput* pizzaBoxSubsystemPBBottonLimit;
	static DigitalInput* pizzaBoxSubsystemPBUpperLimit;
	static DigitalInput* pizzaBoxSubsystemPBLowerLimit;
	static DigitalInput* pizzaBoxSubsystemFrisbeeInPB;
	static Gyro* sensorSubsystemHorizontalGyro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
